# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e72235cecb6333951e6c1a258af1ad652bcc840c96daced1d2568e5319c89ded6c15ad8b09bdb7ca09654a83aa587443aa5236ad24a2a1fd354acd2f94f6f61f

test:
  secret_key_base: 08703406eb0e0d7a0ae02bb8d1b5820c737147fb39bdfaf52632c745a99187e0743d31c9ab0636db770a8584c1ae614904e6dc2271d7893cbb5e346b272dafd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
